# NESTE EXEMPLO, NÃO TEMOS A CHAVE PRIMARIA DEFINIDA
# PARA CONSEGUIR USAR É NECESSÁRIO SEGUIR ESSE PASSOS:
# EDIT -> PREFERNCES -> SQL EDITOR -> OTHERS -> (DESMARQUE) SAFE UPDATES (REJECTS UPDATES AND DELETES ....)
USE sucos;

# atualiza na tabela produto os campos Embalagem e Preço
UPDATE tbproduto SET EMBALAGEM = 'Lata', PRECO_LISTA = 2.46
WHERE PRODUTO = '544931'; # Atualiza no registro '544931'

UPDATE tbproduto SET EMBALAGEM = 'Garrafa'
WHERE PRODUTO = '1078680';

select * FROM tbproduto